name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'  # triggers on tags starting with 'v'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: yourapp-${{ matrix.os }}
          path: |
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.exe
            dist/*.blockmap
            dist/*.yaml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from all OS builds
        uses: actions/download-artifact@v3
        with:
          path: ./release-artifacts

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./release-artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
