name: Build Electron App For All Platforms

on:
  push:
    tags:
      - '*'  # Trigger on any tag push (e.g. v1.0.0)

jobs:
  build:
    name: Build Electron App
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x64
            script: build
          - os: windows-latest
            arch: arm64
            script: build-w-arm
          - os: ubuntu-latest
            arch: x64
            script: build-l
          - os: macos-latest
            arch: universal
            script: build-m
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app (${{ matrix.script }})
        run: npm run ${{ matrix.script }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            dist/*.exe
            dist/*.AppImage
            dist/*.dmg
            dist/*.deb
            dist/**/latest*.yml
            dist/*.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Create Draft GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/**/*.{exe,dmg,AppImage,deb,yml,zip}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
