name: Build Electron App

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build with Electron Builder
        run: npm run build

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: yourapp-build-${{ matrix.os }}
          path: dist/
